trigger:
  - master

pool:
  name: 'Hosted Windows 2019 with VS2019'

steps:

  - task: MSBuild@1
    inputs:
      solution: 'SkiaSharpFunction.sln'
      configuration: 'Release'
      msbuildArguments: '/restore /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:publishUrl=../output'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: 'output'
      includeRootFolder: false
      archiveFile: '$(Build.ArtifactStagingDirectory)/output.zip'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'output'