trigger:
  - master

pool:
  name: 'Hosted Windows 2019 with VS2019'

steps:
  - pwsh: msbuild /restore /p:Configuration=Release /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:publishUrl=../
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'output'
      artifactName: 'output'